apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: gcs-pv
  storageClassName: gcs-storage  # Must match the PV's value
