apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-pv
  namespace: airflow
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcs-storage  # Explicitly set to empty if not using a StorageClass
  csi:
    driver: storage.gke.io
    volumeHandle: "projects/gothic-avenue-444923-e9/buckets/phuongnv63"
    nodeStageSecretRef:
      name: gcs-secret-airflow
      namespace: airflow
