apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcs-storage
provisioner: gcsfuse.csi.storage.gke.io
parameters:
  type: "gcs"                          # Storage type
  bucket: "phuongnv63"                 # Your GCS bucket name
  secretName: "gcs-secret-airflow"     # Kubernetes secret containing GCS credentials
  secretNamespace: "airflow"           # Namespace where the secret exists
reclaimPolicy: Delete
volumeBindingMode: Immediate
