apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcs-storage
provisioner: storage.googleapis.com
parameters:
  type: "gcs"                          # Storage type
  bucket: "phuongnv63"                 # Your GCS bucket name
  secretName: "gcs-secret-airflow"     # Kubernetes secret containing GCS credentials
  secretNamespace: "airflow"           # Namespace where the secret exists
reclaimPolicy: Delete
volumeBindingMode: Immediate
