

ingress:
    enabled: true

webserver:
  enabled: true
  service:
    type: ClusterIP
  serviceAccount:
    automountServiceAccountToken: true
    create: true
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@gothic-avenue-444923-e9.iam.gserviceaccount.com
redis:
  enabled: true

postgresql:
  enabled: true

workers:
  replicas: 1
  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@gothic-avenue-444923-e9.iam.gserviceaccount.com
scheduler:
  replicas: 1
  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@gothic-avenue-444923-e9.iam.gserviceaccount.com
flower:
  enabled: true

triggerer:
  replicas: 1
  serviceAccount:
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@gothic-avenue-444923-e9.iam.gserviceaccount.com
  
resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

logs:
    persistence:
      enabled: false
      existingClaim: airflow-pvc
      size: 100Gi

securityContext:
  runAsUser: 50000
  fsGroup: 50000

airflowPodAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  gke-gcsfuse/volumes: "true"

statefulset:
  triggerer:
    updateStrategy:
      type: RollingUpdate
  worker:
    updateStrategy:
      type: RollingUpdate
