airflow:
  image:
    tag: "2.6.2"

  executor: CeleryExecutor
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: false

dags:
    mountPath: /opt/airflow/dags
    persistence:
      enabled: true
      existingClaim: logs-pvc
      size: 100Gi

ingress:
    enabled: true

webserver:
  enabled: true
  service:
    type: ClusterIP
  serviceAccount:
    automountServiceAccountToken: true
    create: true
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@devops-cms-demo-445215.iam.gserviceaccount.com
redis:
  enabled: true

postgresql:
  enabled: true

workers:
  replicas: 1
  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@devops-cms-demo-445215.iam.gserviceaccount.com

scheduler:
  enabled: true
  replicas: 1
  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@devops-cms-demo-445215.iam.gserviceaccount.com
flower:
  enabled: true

triggerer:
  enabled: true
  replicas: 1
  serviceAccount:
    create: false
    name: phuongnv63
    annotations:
      iam.gke.io/gcp-service-account: storage-admin@devops-cms-demo-445215.iam.gserviceaccount.com

logs:
    persistence:
      enabled: true
      existingClaim: logs-pvc
      size: 100Gi

securityContext:
  runAsUser: 50000
  fsGroup: 50000

airflowPodAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  gke-gcsfuse/volumes: "true"

statefulset:
  triggerer:
    updateStrategy:
      type: RollingUpdate
  worker:
    updateStrategy:
      type: RollingUpdate
